### PR TITLE
Correct method and path for Graph Explore query

### PR DESCRIPTION
**Pull request by oxymor0n**
Fix for #1

### CODE REVIEW

**Comment by honzakral** [comment]
Thanks for the patch! Could I please ask you to sign our CLA (https://www.elastic.co/contributor-agreement/) so I can merge it?

Thanks!

**Comment by oxymor0n** [comment]
@HonzaKral done. Thanks!

**Comment by oxymor0n** [comment]
ah didn't realize I have to confirm my signature with Adobe. It should be good now.

>Individual Contributor License Agreement between elasticsearch BV and William Viet Tran is Signed and Filed!

**Comment by honzakral** [comment]
Thanks for the patch!

**Pull request merged**
